### ISSUE TITLE
Update travis.yml, add clippy, rust fmt

### ISSUE THREAD

**Issue by Liamsi** [w3f/schnorrkel#13]
While skimming through this repo, I've noticed a few things that a .travis.yml exists but still seems to contain arteefacts  from dalek-cryptography? 
https://github.com/w3f/schnorrkel/blob/eaf66334f251984a9a9dd545a1c3bb043da62e12/.travis.yml#L30
I think re-enabling travis, and at least adding rust fmt, clippy, cargo audit (and maybe other lints), would help to keep the code quality high.

**Comment by burdges** [comment]
Yeah there is likely more of this, well this crates started kinda haphazardly.  ;)

**Comment by Liamsi** [comment]
I don't have the permissions to enable travis for this repo. But this is certainly sth. to consider rather sooner than later.

**Comment by burdges** [comment]
Right good point.  I'll try to do that soonish

**Comment by burdges** [comment]
I do not have access to do this on w3f repos but someone should fix that eventually

**Comment by burdges** [comment]
Someone with owner access to w3f turned travis on

**Comment by Liamsi** [comment]
As far as I can tell no travis build was triggered yet though.

**Comment by Liamsi** [comment]
Not sure if that's relevant but this fails to build with the feature `u32_backend` https://travis-ci.org/w3f/schnorrkel/jobs/508081162

**Comment by burdges** [comment]
I never kept up with the full feature set from ed25519-dalek while doing this, so not surprised.  We'll fix them all eventually.

**Comment by Liamsi** [comment]
Probably worth disabling that feature until fixed.
