### ISSUE TITLE
Is this a typo?

### ISSUE THREAD

**Issue by holygits** [w3f/schnorrkel#25]
https://github.com/w3f/schnorrkel/blob/e7238cbfbc2086a6c91e99add11cebf108c6a5dd/src/vrf.rs#L572

Noticed this while working on Substrate and its failing to compile
```rust
error[E0412]: cannot find type `boot` in this scope
   --> /Users/<user>/.cargo/git/checkouts/schnorrkel-0d699dd19a5d19bc/e7238cb/src/vrf.rs:572:34
    |
572 |           F: FnMut(&VRFInOut) -> boot
    |                                  ^^^^ help: a primitive type with a similar name exists: `bool`

```

**Comment by burdges** [comment]
Yes, I noticed it and thought I fixed it immediately, but actually forgot to `git add vrf.rs` before amending the commit.  oops
