### ISSUE TITLE
Does not build

### ISSUE THREAD

**Issue by DemiMarie-parity** [w3f/schnorrkel#28]
The code does not build for me:

       Compiling parity-codec v3.2.0
       Compiling srml-support-procedural v1.0.0 (/home/user/parity/substrate/srml/support/procedural)
        Checking impl-codec v0.2.0
        Checking substrate-trie v1.0.0 (/home/user/parity/substrate/core/trie)
        Checking fork-tree v1.0.0 (/home/user/parity/substrate/core/util/fork-tree)
        Checking finality-grandpa v0.6.0
        Checking primitive-types v0.2.1
        Checking rhododendron v0.5.0
       Compiling jsonrpc-ws-server v10.0.1
       Compiling jsonrpc-http-server v10.0.1
       Compiling schnorrkel v0.1.0
    error: missing angle brackets in associated item path
       --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/serdey.rs:31:37
        |
    31  |                 formatter.write_str($t::DESCRIPTION)
        |                                     ^^^^^^^^^^^^^^^ help: try: `<$t>::DESCRIPTION`
        | 
       ::: /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/points.rs:156:1
        |
    156 | serde_boilerplate!(RistrettoBoth);
        | ---------------------------------- in this macro invocation
    
    error: missing angle brackets in associated item path
       --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/serdey.rs:31:37
        |
    31  |                 formatter.write_str($t::DESCRIPTION)
        |                                     ^^^^^^^^^^^^^^^ help: try: `<$t>::DESCRIPTION`
        | 
       ::: /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/keys.rs:284:1
        |
    284 | serde_boilerplate!(MiniSecretKey);
        | ---------------------------------- in this macro invocation
    
    error: missing angle brackets in associated item path
       --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/serdey.rs:31:37
        |
    31  |                 formatter.write_str($t::DESCRIPTION)
        |                                     ^^^^^^^^^^^^^^^ help: try: `<$t>::DESCRIPTION`
        | 
       ::: /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/keys.rs:502:1
        |
    502 | serde_boilerplate!(SecretKey);
        | ------------------------------ in this macro invocation
    
    error: missing angle brackets in associated item path
       --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/serdey.rs:31:37
        |
    31  |                 formatter.write_str($t::DESCRIPTION)
        |                                     ^^^^^^^^^^^^^^^ help: try: `<$t>::DESCRIPTION`
        | 
       ::: /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/keys.rs:610:1
        |
    610 | serde_boilerplate!(PublicKey);
        | ------------------------------ in this macro invocation
    
    error: missing angle brackets in associated item path
       --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/serdey.rs:31:37
        |
    31  |                 formatter.write_str($t::DESCRIPTION)
        |                                     ^^^^^^^^^^^^^^^ help: try: `<$t>::DESCRIPTION`
        | 
       ::: /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/keys.rs:727:1
        |
    727 | serde_boilerplate!(Keypair);
        | ---------------------------- in this macro invocation
    
    error: missing angle brackets in associated item path
       --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/serdey.rs:31:37
        |
    31  |                 formatter.write_str($t::DESCRIPTION)
        |                                     ^^^^^^^^^^^^^^^ help: try: `<$t>::DESCRIPTION`
        | 
       ::: /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/sign.rs:116:1
        |
    116 | serde_boilerplate!(Signature);
        | ------------------------------ in this macro invocation
    
    error: missing angle brackets in associated item path
       --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/serdey.rs:31:37
        |
    31  |                 formatter.write_str($t::DESCRIPTION)
        |                                     ^^^^^^^^^^^^^^^ help: try: `<$t>::DESCRIPTION`
        | 
       ::: /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/vrf.rs:127:1
        |
    127 | serde_boilerplate!(VRFPut);
        | --------------------------- in this macro invocation
    
    error: missing angle brackets in associated item path
       --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/serdey.rs:31:37
        |
    31  |                 formatter.write_str($t::DESCRIPTION)
        |                                     ^^^^^^^^^^^^^^^ help: try: `<$t>::DESCRIPTION`
        | 
       ::: /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/vrf.rs:353:1
        |
    353 | serde_boilerplate!(VRFProof);
        | ----------------------------- in this macro invocation
    
    error: missing angle brackets in associated item path
       --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/serdey.rs:31:37
        |
    31  |                 formatter.write_str($t::DESCRIPTION)
        |                                     ^^^^^^^^^^^^^^^ help: try: `<$t>::DESCRIPTION`
        | 
       ::: /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/vrf.rs:411:1
        |
    411 | serde_boilerplate!(VRFProofBatchable);
        | -------------------------------------- in this macro invocation
    
    error[E0405]: cannot find trait `Serialize` in this scope
       --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/serdey.rs:17:6
        |
    17  | impl Serialize for $t {
        |      ^^^^^^^^^ not found in this scope
        | 
       ::: /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/vrf.rs:127:1
        |
    127 | serde_boilerplate!(VRFPut);
        | --------------------------- in this macro invocation
    help: possible candidates are found in other modules, you can import them into scope
        |
    69  | use serde::Serialize;
        |
    69  | use serde::ser::Serialize;
        |
    
    error[E0412]: cannot find type `VRFPut` in this scope
       --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/vrf.rs:127:20
        |
    127 | serde_boilerplate!(VRFPut);
        |                    ^^^^^^ not found in this scope
    
    error[E0405]: cannot find trait `Serializer` in this scope
       --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/serdey.rs:18:79
        |
    18  |     fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error> where S: Serializer {
        |                                                                               ^^^^^^^^^^ not found in this scope
        | 
       ::: /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/vrf.rs:127:1
        |
    127 | serde_boilerplate!(VRFPut);
        | --------------------------- in this macro invocation
    help: possible candidates are found in other modules, you can import them into scope
        |
    69  | use serde::Serializer;
        |
    69  | use serde::ser::Serializer;
        |
    
    error[E0405]: cannot find trait `Deserialize` in this scope
       --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/serdey.rs:23:10
        |
    23  | impl<'d> Deserialize<'d> for $t {
        |          ^^^^^^^^^^^ not found in this scope
        | 
       ::: /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/vrf.rs:127:1
        |
    127 | serde_boilerplate!(VRFPut);
        | --------------------------- in this macro invocation
    help: possible candidates are found in other modules, you can import them into scope
        |
    69  | use serde::Deserialize;
        |
    69  | use serde::de::Deserialize;
        |
    
    error[E0405]: cannot find trait `Deserializer` in this scope
       --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/serdey.rs:24:75
        |
    24  |     fn deserialize<D>(deserializer: D) -> Result<Self, D::Error> where D: Deserializer<'d> {
        |                                                                           ^^^^^^^^^^^^ not found in this scope
        | 
       ::: /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/vrf.rs:127:1
        |
    127 | serde_boilerplate!(VRFPut);
        | --------------------------- in this macro invocation
    help: possible candidates are found in other modules, you can import them into scope
        |
    69  | use serde::Deserializer;
        |
    69  | use serde::de::Deserializer;
        |
    
    error[E0405]: cannot find trait `Visitor` in this scope
       --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/serdey.rs:27:18
        |
    27  |         impl<'d> Visitor<'d> for MyVisitor {
        |                  ^^^^^^^ not found in this scope
        | 
       ::: /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/vrf.rs:127:1
        |
    127 | serde_boilerplate!(VRFPut);
        | --------------------------- in this macro invocation
    help: possible candidate is found in another module, you can import it into scope
        |
    69  | use serde::de::Visitor;
        |
    
    error[E0405]: cannot find trait `SerdeError` in this scope
       --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/serdey.rs:34:77
        |
    34  |             fn visit_bytes<E>(self, bytes: &[u8]) -> Result<$t, E> where E: SerdeError{
        |                                                                             ^^^^^^^^^^ not found in this scope
        | 
       ::: /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/vrf.rs:127:1
        |
    127 | serde_boilerplate!(VRFPut);
        | --------------------------- in this macro invocation
    
    error[E0405]: cannot find trait `Serialize` in this scope
       --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/serdey.rs:17:6
        |
    17  | impl Serialize for $t {
        |      ^^^^^^^^^ not found in this scope
        | 
       ::: /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/vrf.rs:353:1
        |
    353 | serde_boilerplate!(VRFProof);
        | ----------------------------- in this macro invocation
    help: possible candidates are found in other modules, you can import them into scope
        |
    69  | use serde::Serialize;
        |
    69  | use serde::ser::Serialize;
        |
    
    error[E0405]: cannot find trait `Serializer` in this scope
       --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/serdey.rs:18:79
        |
    18  |     fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error> where S: Serializer {
        |                                                                               ^^^^^^^^^^ not found in this scope
        | 
       ::: /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/vrf.rs:353:1
        |
    353 | serde_boilerplate!(VRFProof);
        | ----------------------------- in this macro invocation
    help: possible candidates are found in other modules, you can import them into scope
        |
    69  | use serde::Serializer;
        |
    69  | use serde::ser::Serializer;
        |
    
    error[E0405]: cannot find trait `Deserialize` in this scope
       --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/serdey.rs:23:10
        |
    23  | impl<'d> Deserialize<'d> for $t {
        |          ^^^^^^^^^^^ not found in this scope
        | 
       ::: /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/vrf.rs:353:1
        |
    353 | serde_boilerplate!(VRFProof);
        | ----------------------------- in this macro invocation
    help: possible candidates are found in other modules, you can import them into scope
        |
    69  | use serde::Deserialize;
        |
    69  | use serde::de::Deserialize;
        |
    
    error[E0405]: cannot find trait `Deserializer` in this scope
       --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/serdey.rs:24:75
        |
    24  |     fn deserialize<D>(deserializer: D) -> Result<Self, D::Error> where D: Deserializer<'d> {
        |                                                                           ^^^^^^^^^^^^ not found in this scope
        | 
       ::: /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/vrf.rs:353:1
        |
    353 | serde_boilerplate!(VRFProof);
        | ----------------------------- in this macro invocation
    help: possible candidates are found in other modules, you can import them into scope
        |
    69  | use serde::Deserializer;
        |
    69  | use serde::de::Deserializer;
        |
    
    error[E0405]: cannot find trait `Visitor` in this scope
       --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/serdey.rs:27:18
        |
    27  |         impl<'d> Visitor<'d> for MyVisitor {
        |                  ^^^^^^^ not found in this scope
        | 
       ::: /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/vrf.rs:353:1
        |
    353 | serde_boilerplate!(VRFProof);
        | ----------------------------- in this macro invocation
    help: possible candidate is found in another module, you can import it into scope
        |
    69  | use serde::de::Visitor;
        |
    
    error[E0405]: cannot find trait `SerdeError` in this scope
       --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/serdey.rs:34:77
        |
    34  |             fn visit_bytes<E>(self, bytes: &[u8]) -> Result<$t, E> where E: SerdeError{
        |                                                                             ^^^^^^^^^^ not found in this scope
        | 
       ::: /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/vrf.rs:353:1
        |
    353 | serde_boilerplate!(VRFProof);
        | ----------------------------- in this macro invocation
    
    error[E0405]: cannot find trait `Serialize` in this scope
       --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/serdey.rs:17:6
        |
    17  | impl Serialize for $t {
        |      ^^^^^^^^^ not found in this scope
        | 
       ::: /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/vrf.rs:411:1
        |
    411 | serde_boilerplate!(VRFProofBatchable);
        | -------------------------------------- in this macro invocation
    help: possible candidates are found in other modules, you can import them into scope
        |
    69  | use serde::Serialize;
        |
    69  | use serde::ser::Serialize;
        |
    
    error[E0405]: cannot find trait `Serializer` in this scope
       --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/serdey.rs:18:79
        |
    18  |     fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error> where S: Serializer {
        |                                                                               ^^^^^^^^^^ not found in this scope
        | 
       ::: /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/vrf.rs:411:1
        |
    411 | serde_boilerplate!(VRFProofBatchable);
        | -------------------------------------- in this macro invocation
    help: possible candidates are found in other modules, you can import them into scope
        |
    69  | use serde::Serializer;
        |
    69  | use serde::ser::Serializer;
        |
    
    error[E0405]: cannot find trait `Deserialize` in this scope
       --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/serdey.rs:23:10
        |
    23  | impl<'d> Deserialize<'d> for $t {
        |          ^^^^^^^^^^^ not found in this scope
        | 
       ::: /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/vrf.rs:411:1
        |
    411 | serde_boilerplate!(VRFProofBatchable);
        | -------------------------------------- in this macro invocation
    help: possible candidates are found in other modules, you can import them into scope
        |
    69  | use serde::Deserialize;
        |
    69  | use serde::de::Deserialize;
        |
    
    error[E0405]: cannot find trait `Deserializer` in this scope
       --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/serdey.rs:24:75
        |
    24  |     fn deserialize<D>(deserializer: D) -> Result<Self, D::Error> where D: Deserializer<'d> {
        |                                                                           ^^^^^^^^^^^^ not found in this scope
        | 
       ::: /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/vrf.rs:411:1
        |
    411 | serde_boilerplate!(VRFProofBatchable);
        | -------------------------------------- in this macro invocation
    help: possible candidates are found in other modules, you can import them into scope
        |
    69  | use serde::Deserializer;
        |
    69  | use serde::de::Deserializer;
        |
    
    error[E0405]: cannot find trait `Visitor` in this scope
       --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/serdey.rs:27:18
        |
    27  |         impl<'d> Visitor<'d> for MyVisitor {
        |                  ^^^^^^^ not found in this scope
        | 
       ::: /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/vrf.rs:411:1
        |
    411 | serde_boilerplate!(VRFProofBatchable);
        | -------------------------------------- in this macro invocation
    help: possible candidate is found in another module, you can import it into scope
        |
    69  | use serde::de::Visitor;
        |
    
    error[E0405]: cannot find trait `SerdeError` in this scope
       --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/serdey.rs:34:77
        |
    34  |             fn visit_bytes<E>(self, bytes: &[u8]) -> Result<$t, E> where E: SerdeError{
        |                                                                             ^^^^^^^^^^ not found in this scope
        | 
       ::: /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/schnorrkel-0.1.0/src/vrf.rs:411:1
        |
    411 | serde_boilerplate!(VRFProofBatchable);
        | -------------------------------------- in this macro invocation
    
    warning: ignoring -C extra-filename flag due to -o flag
    
    error: aborting due to 28 previous errors
    
    Some errors occurred: E0405, E0412.
    For more information about an error, try `rustc --explain E0405`.
    error: Could not compile `schnorrkel`.
    warning: build failed, waiting for other jobs to finish...
    error: build failed

**Comment by burdges** [comment]
Oops I never published a 0.1.1 after fixing the serde feature in d134645e6a1919d1f4bc41e80ba167f13d351dd3  Fixed now, thanks!
