### ISSUE TITLE
Compatibility between Starsig and Schnorrkel

### ISSUE THREAD

**Issue by oleganza** [w3f/schnorrkel#51]
Hi,

I'd like to make Starsig and Schnorrkel compatible and maybe bikeshed the labels a little. Have you deployed Schnorrkel already, is it hard to update the labels? Would love to hear your thoughts on this:  https://github.com/stellar/slingshot/issues/382

Thanks!

**Comment by burdges** [comment]
Yes, it's deployed in kusama, but not yet in polkadot.  It'd be tricky to change anything, although maybe not impossible if I can sell the devs on the change being important enough.

**Comment by burdges** [comment]
Just fyi I think https://github.com/w3f/schnorrkel/issues/45 will be the most annoying label mess here.  If we do have a very good reason to change labels elsewhere, then maybe I'd try to deal with that in a better way than proposed in that issue.  It's quite tricky to sell though.

**Comment by burdges** [comment]
It'd be very hard to convince folks to throw kusama users under the bus actually.  I've long hoped it'd be a short lived "game of stakes" style thing, but not likely.  The branding is too amusing and folks are even discussing tattoos I hear.  lol

**Comment by burdges** [comment]
I suppose accepting both labels might be one option for compatibility.  We could probably feature gate the label choice somehow, or build it into the SigningTranscript.

**Comment by burdges** [comment]
I suppose our having selected prefix free labels maybe improves something somewhere: 
https://github.com/dalek-cryptography/merlin/issues/62#issuecomment-680291999

**Comment by burdges** [comment]
We'll close this since everything is well established now.
