### ISSUE TITLE
PublicKey incompatible with serde_json

### ISSUE THREAD

**Issue by becominginsane** [w3f/schnorrkel#66]
During testing I encountered an error when trying to deserialize a `PublicKey` from a `serde_json::Value` 

Error:
```
thread 'main' panicked at 'unable to deserialize PublicKey: Error("invalid type: sequence, expected A Ristretto Schnorr public key represented as a 32-byte Ristretto compressed point", line: 0, column: 0)', src/main.rs:11:40
```

example code can be found [here](https://github.com/becominginsane/schnorrkel-serde).

I think this can be fixed in multiple ways, either by implementing `visit_seq` or by making use of [serde_bytes](https://docs.rs/serde_bytes/0.11.5/serde_bytes/) (even tho it will probably mean that it'll be necessary to wrap with `Bytes` during serialization / deserialization manually instead of using the attributes offered)

**Comment by burdges** [comment]
Can you explain what fails in https://github.com/w3f/schnorrkel/blob/master/src/serdey.rs please?  

A priori I'd expect `visit_seq` should fail when invoked upon a simple byte array because that's what `visit_bytes` does, no?

**Comment by Karrq** [comment]
I don't understand why was the issue closed...?
There's nothing failing per se in serdey.rs, but some formats (like serde_json) don't specialize sequence of bytes in bytes, that's why in this case deserialization fails with the reported error...

**Comment by becominginsane** [comment]
I don't understand why the issue was closed...?
There's nothing failing in serdey per se, it's just that not all format specialise sequence of bytes as just bytes, json being one of those...
This poses an issue with the current implementation during deserialization, with the reported error, where a sequence is encountered but serdey doesn't handle it

**Comment by burdges** [comment]
I just pressed the wrong button..

**Comment by becominginsane** [comment]
There's a problem in implementing the deserialization part, namely a `BytesBuf` becomes somewhat necessary if you want sequence support since `Bytes` doesn't implement `visit_sequence`, probably since the size is now known so you'd need to allocate. 
I'm probably gonna impl with `Bytes` and if `alloc` is provided as feature then use `BytesBuf` instead

**Comment by burdges** [comment]
I think a serde_bytes feature flag sounds good, mostly because ed25519-dalek did so.
