### ISSUE TITLE
Build fails: `rand_core` doesn't have feature `nightly`

### ISSUE THREAD

**Issue by mmagician** [w3f/schnorrkel#84]
```
the package `schnorrkel` depends on `rand_core`, with features: `nightly` but `rand_core` does not have these features.
```

I went through a couple of older versions of rand_core, but none of these seem to have the nightly feature?
e.g. https://github.com/rust-random/rand/blob/rand_core-0.5.0/rand_core/Cargo.toml

**Comment by burdges** [comment]
cool thanks, you need a new version published soonish?

**Comment by mmagician** [comment]
no, just benchmarking locally
