### ISSUE TITLE
Update from curve25519-dalek 4.0.0-rc2 to 4.0.0 and release 0.11

### ISSUE THREAD

**Issue by kayabaNerve** [w3f/schnorrkel#89]
Now that curve25519-dalek 4.0.0 has been released, it'd be extremely appreciated if schnorrkel would update and publish a release with said update. I understand if 0.11 is pending other changes, either regarding dependencies, functionality, or API, yet still wanted to make the request. At the very least, a timeline would be very appreciated.

**Comment by koute** [comment]
Already on my TODO list. I will get to it soon as soon as I finish what I'm doing now.

**Comment by burdges** [comment]
It's done

**Comment by kayabaNerve** [comment]
Thank you!
